### ISSUE TITLE
Double escaping

### ISSUE THREAD

**Issue by damianwajer** [Within3/liquid-autoescape#1]
I’d like to suggest changing `escape` filter to `escape_once` in order to prevent double escaping.

Right now:

```
{% assign variable = "<strong>test</strong>" %}
{{ variable }}
```

is escaped to:

```
&amp;lt;strong&amp;gt;test&amp;lt;/strong&amp;gt;
```

but I think expected output would be:

```
&lt;strong&gt;test&lt;/strong&gt;
```

`escape_once` does exactly that, so `{{ variable | escape_once | escape_once }}` is always escaped correctly as `&lt;strong&gt;test&lt;/strong&gt;`

https://shopify.github.io/liquid/filters/escape_once/

It would be useful instead of a need to use `skip_escape` in all such cases

```
{% assign variable = "<strong>test</strong>" | skip_escape %}
{{ variable }}
```

**Comment by justinlocsei** [comment]
Thanks for posting this, @damianwajer !  I looked into using `escape_once` instead of `escape`, but chose not to go with it, at least for now.  While it would handle the case of double-escaping `assign`ed values, `escape_once` is using a regex to determine if something has already been escaped, and I'm not certain if that's a robust enough approach to handle all possible inputs without surprises.  I fully admit to this probably just being paranoia, especially since there's also a precedent for `escape_once` in Rails, but we're using this gem to show a large amount of data in production, and I'd prefer to not change a fundamental assumption of how escaping is applied.

However, I did push v2.0.0 of this gem recently, which adds the ability to disable auto-escaping by wrapping template code in an `{% autoescape false %}...{% endautoescape %}` block, which might make things less painful if you're doing a bunch of `assign` statements in a row.  I know it's not perfect, but it might help!
