### ISSUE TITLE
Values assigned via `assign` are escaped

### ISSUE THREAD

**Issue by zyla** [Within3/liquid-autoescape#2]
Use of `assign` within an `autoescape` block causes the assigned value to be escaped.

I believe this is the root cause of https://github.com/Within3/liquid-autoescape/issues/1.

Test case:

```diff
diff --git a/spec/functional/autoescape_tag_spec.rb b/spec/functional/autoescape_tag_spec.rb
index 662b30a..45207b4 100644
--- a/spec/functional/autoescape_tag_spec.rb
+++ b/spec/functional/autoescape_tag_spec.rb
@@ -53,6 +53,13 @@ describe "{% autoescape %}" do
     )
   end
 
+  it "does not escape in assign" do
+    verify_template_output(
+      "{% autoescape %}{% assign variable = \"&\" %}{% endautoescape %}{{ variable }}",
+      "&"
+    )
+  end
+
   it "does not escape variables outside the block tag" do
     verify_template_output(
       "{{ variable }} {% autoescape %}{{ variable }}{% endautoescape %} {{ variable }}",
```

**Comment by justinlocsei** [comment]
Thank you for reporting this issue, @zyla , and sorry for taking so long to respond to it!  I did some digging through all of the Liquid versions targeted by this gem, and I didn't see an immediately obvious way to skip escaping for assigned variables.  Since `assign`s are created by pre-rendering a variable using the same `Liquid::Variable#render` method used for showing a variable surrounded by curly brackets, I didn't see a way to figure out if that variable was being pre-rendered as part of an `assign` tag.

However, I did just push v2.0.0 of this gem, which adds the ability to opt in or out of auto-escaping by passing a boolean to the `{% autoescape %}` tag, which works either inside a local `{% autoescape %}` context or with global auto-escaping on.  This could be used to handle the issue of the preemptively escaped `assign`s as follows:

```liquid
{% autoescape %}
  {% assign escaped = "&" %}

  {% autoescape false %}
    {% assign not_escaped = "&" %}
  {% endautoescape %}
{% endautoescape %}

{{ escaped }} <!-- "&amp;" -->
{{ not_escaped }} <!-- "&" -->
```

We're using this in production to handle cases where we have global auto-escaping on and need to opt out of it in the context of a `{% block %}` tag whose body is being used to populate a `<script>` tag with JSON, and it's working out well for us.  I know this doesn't exactly address the issue of the surprising behavior of `{% assign %}` escaping its variables, but I hope it should provide you with the flexibility to work around this.

Let me know if this addresses your issue when you get a chance.  It took me almost a year to respond to your post, so there's no rush getting back to me!
